apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: shoowee-es-tls
spec:
  secretName: shoowee-es
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: shoowee.es
  dnsNames:
    - shoowee.es
    - www.shoowee.es
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - shoowee.es
          - www.shoowee.es
